### ISSUE TITLE
Add Loader for fetch location

### ISSUE THREAD

**Issue by rajam1215** [anirudhmpai/EasyLocationFetch#12]
Need to add one loader when location fetch in any area, **_because on click of button some time , location not come instantly_**, if location come it is OK, **_but if location finding take time , then need to show loader_**

**_and need to clear last location data_**, when new location fetch from places Api, GPS provider, Passive and Network Provider

**Comment by anirudhmpai** [comment]
@rajam1215 thank you for the suggestion, will add it to the example app when I get some free time.

In the meantime, you can just call the EasyLocationFetch function and add it to your custom button with the said functionality and it will work without issues.
